"""add impersonation to scan_records

Revision ID: 0ed86c60d55a
Revises: b6d4205f1105
Create Date: 2026-10-02 15:12:00.051844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed86c60d55a'
down_revision = 'b6d4205f1105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impersonation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('impersonation')

    # ### end Alembic commands ###
