"""add engine_version to scan_records

Revision ID: 197c5af39b62
Revises: b0f3a8070f84
Create Date: 2026-10-01 17:27:51.454846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197c5af39b62'
down_revision = 'b0f3a8070f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_version', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('engine_version')

    # ### end Alembic commands ###
