"""initial schema

Revision ID: 3120e355e6b2
Revises: 
Create Date: 2026-06-23 16:38:30.628059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3120e355e6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cert_hash', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('malicious_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_records_cert_hash'), ['cert_hash'], unique=True)

    op.create_table('scan_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('ml_class', sa.String(length=50), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('signature_verdict', sa.String(length=20), nullable=True),
    sa.Column('vt_detection_ratio', sa.String(length=20), nullable=True),
    sa.Column('androguard_data', sa.JSON(), nullable=True),
    sa.Column('vt_data', sa.JSON(), nullable=True),
    sa.Column('sandbox_data', sa.JSON(), nullable=True),
    sa.Column('ml_explanation', sa.JSON(), nullable=True),
    sa.Column('cert_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cert_hash'], ['certificate_records.cert_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_records_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_records_package_name'), ['package_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_records_package_name'))
        batch_op.drop_index(batch_op.f('ix_scan_records_file_hash'))

    op.drop_table('scan_records')
    with op.batch_alter_table('certificate_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_records_cert_hash'))

    op.drop_table('certificate_records')
    # ### end Alembic commands ###
