"""add signal_scores and model_agreement

Revision ID: 318b7f9afb8d
Revises: 63aa98a4ea0d
Create Date: 2026-07-04 11:49:40.576985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318b7f9afb8d'
down_revision = '63aa98a4ea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('model_agreement', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('model_agreement')
        batch_op.drop_column('signal_scores')

    # ### end Alembic commands ###
