"""add static ml columns to scan records

Revision ID: 63aa98a4ea0d
Revises: 3120e355e6b2
Create Date: 2026-06-29 07:29:06.674296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aa98a4ea0d'
down_revision = '3120e355e6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static_ml_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('static_ml_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('static_ml_confidence')
        batch_op.drop_column('static_ml_class')

    # ### end Alembic commands ###
