"""add ioc_summary to scan_records

Revision ID: 75aaac25f5a6
Revises: 318b7f9afb8d
Create Date: 2026-07-16 16:39:21.687514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aaac25f5a6'
down_revision = '318b7f9afb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ioc_summary', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('ioc_summary')

    # ### end Alembic commands ###
