"""risk_score float and risk_floor

Revision ID: acf2e13eb044
Revises: 0ed86c60d55a
Create Date: 2026-10-02 16:20:11.474476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf2e13eb044'
down_revision = '0ed86c60d55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_floor', sa.Float(), nullable=True))
        batch_op.alter_column('risk_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="risk_score::double precision")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.alter_column('risk_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('risk_floor')

    # ### end Alembic commands ###
