"""add scan_type to scan_records

Revision ID: b0f3a8070f84
Revises: 75aaac25f5a6
Create Date: 2026-10-01 16:42:56.761612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f3a8070f84'
down_revision = '75aaac25f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('scan_type')

    # ### end Alembic commands ###
