"""add report fields and error_message

Revision ID: b6d4205f1105
Revises: 197c5af39b62
Create Date: 2026-10-02 12:37:43.387564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d4205f1105'
down_revision = '197c5af39b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threat_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confidence_level', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('signals_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('signals_used')
        batch_op.drop_column('confidence_level')
        batch_op.drop_column('threat_summary')

    # ### end Alembic commands ###
