"""add_risk_floor_reason_to_scan_records

Revision ID: dd45e64d6e04
Revises: acf2e13eb044
Create Date: 2026-10-03 12:57:20.091727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd45e64d6e04'
down_revision = 'acf2e13eb044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_floor_reason', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('risk_floor_reason')

    # ### end Alembic commands ###
